/* Generated by froam-studio (Repo Mode) — do not edit by hand.
   Zero-dependency Froam runtime: route attribute + text/image/injected
   drafts for sites that don't mount the React <FroamRuntime/>. */
;(function () {
  'use strict'
  if (typeof window === 'undefined' || typeof document === 'undefined') return
  if (window.__FROAM_VANILLA_RUNTIME__) return
  window.__FROAM_VANILLA_RUNTIME__ = true

  var DESIGN = {"version":3,"routes":{}}
  var CANVAS_KEY = '__froam_canvas__'
  var INJECTION_PREFIX = '__froam_injection__:'
  var SECTION_STRUCTURE_KEY = '__froam_structure__:sections'
  var ROOT_PARENT_KEY = '__froam_root__'
  var TEXT_TAGS = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span', 'small', 'strong', 'em', 'b', 'i', 'label', 'button', 'a', 'li']

  function getRoot() {
    if (DESIGN.rootScope === 'page') return document.body
    return (
      document.querySelector('[data-froam-root]') ||
      document.getElementById('root') ||
      document.getElementById('__next') ||
      document.querySelector('main') ||
      document.body
    )
  }

  function viewportMode() {
    if (window.matchMedia('(max-width: 640px)').matches) return 'mobile'
    if (window.matchMedia('(max-width: 1024px)').matches) return 'tablet'
    return 'desktop'
  }

  // "@body/…" paths are content beside the root (a React app's portals),
  // counted from <body>. Froam's own nodes there never count.
  var BODY_PREFIX = '@body/'
  function isFroamOwned(element) {
    return element.getAttribute('data-chef-editor-root') === 'true' || (element.id || '').indexOf('froam-') === 0
  }

  function findByPath(root, pathValue) {
    var fromBody = pathValue.indexOf(BODY_PREFIX) === 0
    var segments = (fromBody ? pathValue.slice(BODY_PREFIX.length) : pathValue).split('/').filter(Boolean)
    var current = fromBody ? document.body : root
    for (var i = 0; i < segments.length; i += 1) {
      var pieces = segments[i].split(':')
      var tag = pieces[0]
      var index = Number(pieces[1]) - 1
      if (!tag || isNaN(index) || index < 0 || !current) return null
      var matches = []
      var onBody = current === document.body
      for (var c = 0; c < current.children.length; c += 1) {
        var child = current.children[c]
        if (child.tagName && child.tagName.toLowerCase() === tag && !(onBody && isFroamOwned(child))) matches.push(child)
      }
      current = matches[index] || null
    }
    return current
  }

  function canApplyText(element) {
    var tag = element.tagName.toLowerCase()
    if (tag === 'input' || tag === 'textarea') return false
    if (element.children.length === 0) return true
    return TEXT_TAGS.indexOf(tag) !== -1
  }

  // innerText reads back normalised ("Hello " → "Hello"), so what the element
  // showed right after the last write is remembered: still showing exactly
  // that means the draft is on screen, and rewriting would only churn the DOM.
  var shownAfterWrite = typeof WeakMap === 'function' ? new WeakMap() : null
  function applyText(element, text) {
    var shown = element.innerText
    if (shown === text) return
    var last = shownAfterWrite && shownAfterWrite.get(element)
    if (last && last.text === text && last.shown === shown) return
    element.innerText = text
    if (shownAfterWrite) shownAfterWrite.set(element, { text: text, shown: element.innerText })
  }

  function clearInjected(root) {
    var injected = root.querySelectorAll('[data-froam-runtime-injected="true"]')
    for (var i = 0; i < injected.length; i += 1) injected[i].parentNode.removeChild(injected[i])
  }

  function ensureRuntimeVisibilityStyle() {
    var style = document.getElementById('froam-runtime-visibility')
    if (!style) {
      style = document.createElement('style')
      style.id = 'froam-runtime-visibility'
      document.head.appendChild(style)
    }
    style.textContent = 'html:not([data-chef-editing]) [data-froam-export-hidden="true"],html:not([data-chef-editing]) [data-froam-structure-deleted="true"]{display:none!important}'
  }

  function applySectionStructure(root, store) {
    var draft = store[SECTION_STRUCTURE_KEY]
    if (!draft || !draft.text) return
    var manifest
    try { manifest = JSON.parse(draft.text) } catch (e) { return }
    if (!manifest || !Array.isArray(manifest.sections)) return
    var resolved = []
    for (var i = 0; i < manifest.sections.length; i += 1) {
      var entry = manifest.sections[i]
      if (!entry || typeof entry.sourcePath !== 'string' || typeof entry.nodeId !== 'string') continue
      var element = root.querySelector('[data-froam-id="' + entry.nodeId.replace(/["\\]/g, '\\$&') + '"]') || findByPath(root, entry.sourcePath)
      if (!element || element.getAttribute('data-froam-runtime-injected') === 'true') continue
      element.setAttribute('data-froam-id', entry.nodeId)
      element.setAttribute('data-froam-structure-source', entry.sourcePath)
      resolved.push({ entry: entry, element: element })
    }
    resolved.filter(function (item) { return !item.entry.deleted }).sort(function (a, b) { return a.entry.order - b.entry.order }).forEach(function (item) {
      var parent = item.entry.parentPath === ROOT_PARENT_KEY ? root : findByPath(root, item.entry.parentPath)
      if (parent) {
        var current = Array.prototype.indexOf.call(parent.children, item.element)
        if (current !== item.entry.order) {
          item.element.remove()
          parent.insertBefore(item.element, parent.children.item(item.entry.order))
        }
      }
      item.element.hidden = !!item.entry.exportHidden
      if (item.entry.exportHidden) item.element.setAttribute('data-froam-export-hidden', 'true')
      else item.element.removeAttribute('data-froam-export-hidden')
    })
    resolved.filter(function (item) { return !!item.entry.deleted }).forEach(function (item) {
      item.element.hidden = true
      item.element.setAttribute('data-froam-structure-deleted', 'true')
    })
  }

  function applyInjections(root, store) {
    var blocks = []
    for (var key in store) {
      if (key.indexOf(INJECTION_PREFIX) !== 0 || !store[key].text) continue
      try {
        var parsed = JSON.parse(store[key].text)
        if (typeof parsed.html === 'string' && typeof parsed.parentPath === 'string') {
          blocks.push({ html: parsed.html, parentPath: parsed.parentPath, parentId: typeof parsed.parentId === 'string' ? parsed.parentId : '', order: typeof parsed.order === 'number' ? parsed.order : 0 })
        }
      } catch (e) { /* skip malformed */ }
    }
    blocks.sort(function (a, b) { return a.order - b.order })
    for (var i = 0; i < blocks.length; i += 1) {
      var parent = blocks[i].parentId ? root.querySelector('[data-froam-id="' + blocks[i].parentId.replace(/["\\]/g, '\\$&') + '"]') : blocks[i].parentPath === ROOT_PARENT_KEY ? root : findByPath(root, blocks[i].parentPath)
      if (!parent) continue
      var template = document.createElement('template')
      template.innerHTML = blocks[i].html.trim()
      var node = template.content.firstElementChild
      if (!node) continue
      node.setAttribute('data-froam-runtime-injected', 'true')
      node.removeAttribute('data-chef-selected')
      node.removeAttribute('data-chef-hovered')
      // Blocks saved before 8.5 carried contenteditable — never live for visitors.
      node.removeAttribute('contenteditable')
      var editables = node.querySelectorAll('[contenteditable]')
      for (var e = 0; e < editables.length; e += 1) editables[e].removeAttribute('contenteditable')
      parent.insertBefore(node, parent.children.item(blocks[i].order))
    }
  }

  function applyCustomCss(css) {
    var styleEl = document.getElementById('froam-global-styles')
    if (css) {
      if (!styleEl) {
        styleEl = document.createElement('style')
        styleEl.id = 'froam-global-styles'
        document.head.appendChild(styleEl)
      }
      if (styleEl.textContent !== css) styleEl.textContent = css
    } else if (styleEl) {
      styleEl.textContent = ''
    }
  }

  function normRoute(value) {
    var p = String(value || '/').split('?')[0].split('#')[0]
    p = p.replace(/\/index\.html?$/i, '/')
    p = p.replace(/\/+$/, '')
    return p || '/'
  }

  function apply() {
    if (document.documentElement.hasAttribute('data-chef-editing')) return
    var routeKey = normRoute(window.location.pathname)
    document.documentElement.setAttribute('data-froam-route', routeKey)

    var root = getRoot()
    if (!root) return
    if (!root.hasAttribute('data-froam-root')) root.setAttribute('data-froam-root', '')

    clearInjected(root)
    var route = DESIGN.routes[routeKey]
    var store = route && route[viewportMode()]
    if (!store) { applyCustomCss(''); return }

    applySectionStructure(root, store)
    applyInjections(root, store)

    for (var key in store) {
      if (key === CANVAS_KEY) { applyCustomCss(store[key].customCSS || ''); continue }
      if (key.indexOf('__froam') === 0) continue
      var target = findByPath(root, key)
      if (!target) continue
      var draft = store[key]
      if (draft.text !== undefined && canApplyText(target)) applyText(target, draft.text)
      if (draft.imageUrl !== undefined && target.tagName.toLowerCase() === 'img') {
        if (draft.imageUrl && target.getAttribute('src') !== draft.imageUrl) target.src = draft.imageUrl
        if (!draft.imageUrl && target.hasAttribute('src')) target.removeAttribute('src')
      }
    }
  }

  var frame = 0
  var observer = null
  // apply() re-injects blocks and rewrites text, which mutates the root; those
  // records are the runtime's own — left queued, they'd schedule the next
  // apply and rebuild every injected block on every frame.
  function applyOwnChanges() {
    apply()
    if (observer) observer.takeRecords()
  }
  function scheduleApply() {
    cancelAnimationFrame(frame)
    frame = requestAnimationFrame(applyOwnChanges)
  }

  function patchHistory(method) {
    var original = window.history[method]
    window.history[method] = function () {
      var result = original.apply(this, arguments)
      scheduleApply()
      return result
    }
  }

  function start() {
    ensureRuntimeVisibilityStyle()
    apply()
    patchHistory('pushState')
    patchHistory('replaceState')
    window.addEventListener('popstate', scheduleApply)
    window.addEventListener('resize', scheduleApply)
    var root = getRoot()
    if (root && typeof MutationObserver !== 'undefined') {
      observer = new MutationObserver(function (mutations) {
        for (var i = 0; i < mutations.length; i += 1) {
          var node = mutations[i].target
          if (node && node.closest && node.closest('[data-froam-runtime-injected="true"], [data-chef-editor-root]')) continue
          scheduleApply()
          return
        }
      })
      // A portal's modal mounts on <body>, long after load: watch it too.
      observer.observe(hasBodyPaths() && root !== document.body ? document.body : root, { childList: true, subtree: true })
    }
  }

  function hasBodyPaths() {
    for (var routeKey in DESIGN.routes) {
      var viewports = DESIGN.routes[routeKey]
      for (var viewport in viewports) {
        for (var key in viewports[viewport]) if (key.indexOf(BODY_PREFIX) === 0) return true
      }
    }
    return false
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', start)
  else start()
})()
